import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart' as p;
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:file_picker/file_picker.dart';
import 'package:csv/csv.dart';
import 'package:excel/excel.dart' as excel;
import 'package:http/http.dart' as http;
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

const bg=Color(0xFF071A35), card=Color(0xFF102A4D), blue=Color(0xFF2563EB), gold=Color(0xFFF59E0B), green=Color(0xFF10B981), red=Color(0xFFEF4444), muted=Color(0xFF9FB2CC);
String money(num n)=>NumberFormat('#,##0.00','en_US').format(n);
String dtext(dynamic v){final d=DateTime.tryParse('$v');return d==null?'$v':DateFormat('yyyy/MM/dd').format(d);}

class DB{static Database? _d;static Future<Database> get d async{if(_d!=null)return _d!;final f=p.join(await getDatabasesPath(),'smart_assistant.db');return _d=await openDatabase(f,version:1,onCreate:(db,v)async{await db.execute('CREATE TABLE customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,notes TEXT,created TEXT)');await db.execute('CREATE TABLE products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,category TEXT,qty REAL,minimum REAL,price REAL,created TEXT)');await db.execute('CREATE TABLE dues(id INTEGER PRIMARY KEY AUTOINCREMENT,customer TEXT,amount REAL,due TEXT,note TEXT,status TEXT)');await db.execute('CREATE TABLE transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,customer TEXT,type TEXT,amount REAL,note TEXT,date TEXT)');});}}

class AppState extends ChangeNotifier{void setTab(int i){tab=i;notifyListeners();}int tab=0;Map<String,dynamic> st={};List<Map<String,dynamic>> customers=[],products=[],dues=[];String key='',model='openai/gpt-oss-20b:free',base='https://openrouter.ai/api/v1/chat/completions';Future<void> init()async{final q=await SharedPreferences.getInstance();key=q.getString('key')??'';model=q.getString('model')??model;base=q.getString('base')??base;await refresh();}Future<void> refresh()async{final db=await DB.d;customers=await db.query('customers',orderBy:'name');products=await db.query('products',orderBy:'name');dues=await db.query('dues',orderBy:'due');final c=(await db.rawQuery('SELECT COUNT(*) n FROM customers')).first['n'] as int;final pr=(await db.rawQuery('SELECT COUNT(*) n FROM products')).first['n'] as int;final low=(await db.rawQuery('SELECT COUNT(*) n FROM products WHERE qty<=minimum')).first['n'] as int;final du=(await db.rawQuery('SELECT COUNT(*) n FROM dues WHERE status="pending"')).first['n'] as int;final owed=(await db.rawQuery('SELECT COALESCE(SUM(amount),0) n FROM transactions WHERE type="debt"')).first['n'] as num;final paid=(await db.rawQuery('SELECT COALESCE(SUM(amount),0) n FROM transactions WHERE type="payment"')).first['n'] as num;st={'customers':c,'products':pr,'low':low,'dues':du,'owed':owed.toDouble(),'paid':paid.toDouble()};notifyListeners();}Future<void> saveAI(String k,String m,String b)async{final q=await SharedPreferences.getInstance();await q.setString('key',k);await q.setString('model',m);await q.setString('base',b);key=k;model=m;base=b;notifyListeners();}}

Future<void> editor(BuildContext c,String title,List<Map<String,dynamic>> fs,Future<void> Function(Map<String,String>) save)async{final cs={for(final f in fs)f['k'] as String:TextEditingController(text:'${f['v']??''}')};await showDialog(context:c,builder:(x)=>AlertDialog(backgroundColor:card,title:Text(title),content:SingleChildScrollView(child:Column(children:[for(final f in fs)Padding(padding:const EdgeInsets.only(bottom:9),child:TextField(controller:cs[f['k']],keyboardType:f['num']==true?TextInputType.number:TextInputType.text,decoration:InputDecoration(labelText:f['l'] as String)))])),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('إلغاء')),FilledButton(onPressed:()async{await save({for(final e in cs.entries)e.key:e.value.text});if(x.mounted)Navigator.pop(x);},child:const Text('حفظ'))]));for(final x in cs.values)x.dispose();}

Future<void> main()async{WidgetsFlutterBinding.ensureInitialized();final s=AppState();await s.init();runApp(ChangeNotifierProvider.value(value:s,child:const App()));}
class App extends StatelessWidget{const App({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'المساعد الذكي',theme:ThemeData.dark().copyWith(scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:blue,brightness:Brightness.dark),inputDecorationTheme:InputDecorationTheme(filled:true,fillColor:card,border:OutlineInputBorder(borderRadius:BorderRadius.circular(14),borderSide:BorderSide.none)),navigationBarTheme:NavigationBarThemeData(backgroundColor:const Color(0xFF0B2344),indicatorColor:blue)),home:const Root());}
class Root extends StatelessWidget{const Root({super.key});@override Widget build(BuildContext c){final s=c.watch<AppState>();final pages=[const Home(),const Customers(),const Products(),const Reports(),const More()];return Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:SafeArea(child:pages[s.tab]),bottomNavigationBar:NavigationBar(selectedIndex:s.tab,onDestinationSelected:(i){s.setTab(i);},destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'الرئيسية'),NavigationDestination(icon:Icon(Icons.people_outline),selectedIcon:Icon(Icons.people),label:'العملاء'),NavigationDestination(icon:Icon(Icons.inventory_2_outlined),selectedIcon:Icon(Icons.inventory_2),label:'الأصناف'),NavigationDestination(icon:Icon(Icons.bar_chart_outlined),selectedIcon:Icon(Icons.bar_chart),label:'التقارير'),NavigationDestination(icon:Icon(Icons.more_horiz),label:'المزيد')])));}}

class Home extends StatelessWidget{const Home({super.key});@override Widget build(BuildContext c){final s=c.watch<AppState>(),x=s.st;return ListView(padding:const EdgeInsets.all(15),children:[Row(children:[IconButton(onPressed:()=>showModalBottomSheet(context:c,backgroundColor:card,builder:(_)=>const More()),icon:const Icon(Icons.menu)),const Spacer(),const Column(children:[Text('المساعد الذكي',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),Text('إدارة العملاء والمخزون بذكاء',style:TextStyle(color:muted,fontSize:11))]),const Spacer(),IconButton(onPressed:()=>showDialog(context:c,builder:(_)=>const AlertDialog(backgroundColor:card,title:Text('التنبيهات'),content:Text('تابع الاستحقاقات والأصناف الناقصة من التطبيق.'))),icon:const Icon(Icons.notifications_none))]),Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF173D6D),Color(0xFF0D284B)]),borderRadius:BorderRadius.circular(18)),child:const Column(crossAxisAlignment:CrossAxisAlignment.end,children:[Text('👋 مرحباً بك',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),SizedBox(height:5),Text('إليك نظرة عامة على نشاطك اليوم',style:TextStyle(color:muted))])),const SizedBox(height:12),GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,mainAxisSpacing:10,crossAxisSpacing:10,childAspectRatio:1.5,children:[K('إجمالي الأرصدة',money(x['owed']??0),'إجمالي الرصيد',green),K('العملاء','${x['customers']??0}','إجمالي العملاء',blue),K('استحقاقات اليوم','${x['dues']??0}','استحقاق',gold),K('العملاء المنسيون','${math.min<int>((x['customers'] as int?) ?? 0,18)}','عميل',red),K('الأصناف','${x['products']??0}','إجمالي الأصناف',blue),K('الأصناف الناقصة','${x['low']??0}','صنف',red)]),const SizedBox(height:12),Balance(owed:((x['owed'] as num?) ?? 0).toDouble(),paid:((x['paid'] as num?) ?? 0).toDouble()),const SizedBox(height:12),const DuesPreview()] );}}
class K extends StatelessWidget{final String a,b,c;final Color col;const K(this.a,this.b,this.c,this.col,{super.key});@override Widget build(BuildContext x)=>Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:card,borderRadius:BorderRadius.circular(16)),child:Column(crossAxisAlignment:CrossAxisAlignment.end,children:[Text(a,style:const TextStyle(fontSize:12)),const Spacer(),Text(b,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text(c,style:const TextStyle(color:muted,fontSize:10))]));}
class Balance extends StatelessWidget{final double owed,paid;const Balance({required this.owed,required this.paid,super.key});@override Widget build(BuildContext c){final t=owed+paid;return Card(color:card,child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.end,children:[const Text('نظرة عامة على الأرصدة',style:TextStyle(fontWeight:FontWeight.bold,fontSize:16)),const SizedBox(height:12),Row(children:[SizedBox(width:105,height:105,child:CustomPaint(painter:Donut(owed,paid))),const SizedBox(width:15),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.end,children:[Text('لهم   ${money(paid)}',style:const TextStyle(color:green)),const SizedBox(height:12),Text('عليهم   ${money(owed)}',style:const TextStyle(color:red)),const SizedBox(height:12),Text('الإجمالي   ${money(t)}',style:const TextStyle(fontWeight:FontWeight.bold))]))]))]));}}
class Donut extends CustomPainter{final double a,b;Donut(this.a,this.b);@override void paint(Canvas x,Size s){final p=Paint()..style=PaintingStyle.stroke..strokeWidth=18;final r=Rect.fromCircle(center:s.center(Offset.zero),radius:s.width*.34),t=a+b;final aa=t==0?0:2*math.pi*b/t;p.color=green;x.drawArc(r,-math.pi/2,aa,false,p);p.color=red;x.drawArc(r,-math.pi/2+aa,t==0?0:2*math.pi*a/t,false,p);}@override bool shouldRepaint(covariant Donut o)=>o.a!=a||o.b!=b;}
class DuesPreview extends StatelessWidget{const DuesPreview({super.key});@override Widget build(BuildContext c){final s=c.watch<AppState>();return Card(color:card,child:Padding(padding:const EdgeInsets.all(12),child:Column(children:[Row(children:[const Text('أقرب الاستحقاقات',style:TextStyle(fontWeight:FontWeight.bold,fontSize:16)),const Spacer(),TextButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Dues())),child:const Text('عرض الكل'))]),...s.dues.take(3).map((r)=>ListTile(dense:true,title:Text(money(r['amount'])),subtitle:Text('${r['customer']??''} • ${dtext(r['due'])}'),leading:const Icon(Icons.event,color:gold)))])));}}

class Customers extends StatefulWidget{const Customers({super.key});@override State<Customers> createState()=>_CS();}
class _CS extends State<Customers>{String q='';@override Widget build(BuildContext c){final s=c.watch<AppState>();final rows=s.customers.where((r)=>'${r['name']} ${r['phone']}'.contains(q)).toList();return Scaffold(appBar:AppBar(title:const Text('العملاء')),floatingActionButton:FloatingActionButton(backgroundColor:blue,onPressed:()=>add(c),child:const Icon(Icons.add)),body:ListView(padding:const EdgeInsets.all(14),children:[TextField(onChanged:(v)=>setState(()=>q=v),decoration:const InputDecoration(hintText:'بحث عن عميل...',prefixIcon:Icon(Icons.search))),const SizedBox(height:10),if(rows.isEmpty)const Empty('لا يوجد عملاء بعد'),...rows.map((r)=>Card(color:card,child:ListTile(title:Text(r['name']),subtitle:Text(r['phone']??''),leading:const Icon(Icons.person_outline,color:blue),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()async{await DB.d.then((d)=>d.delete('customers',where:'id=?',whereArgs:[r['id']]));await c.read<AppState>().refresh();}))))]));}Future<void> add(BuildContext c)async{await editor(c,'إضافة عميل',const[{'k':'name','l':'اسم العميل'},{'k':'phone','l':'رقم الهاتف'},{'k':'notes','l':'ملاحظات'}],(v)async{if(v['name']!.trim().isEmpty)return;await DB.d.then((d)=>d.insert('customers',{'name':v['name'],'phone':v['phone'],'notes':v['notes'],'created':DateTime.now().toIso8601String()}));await c.read<AppState>().refresh();});}}

class Products extends StatefulWidget{const Products({super.key});@override State<Products> createState()=>_PS();}
class _PS extends State<Products>{String q='';@override Widget build(BuildContext c){final s=c.watch<AppState>();final rows=s.products.where((r)=>'${r['name']} ${r['category']}'.contains(q)).toList();return Scaffold(appBar:AppBar(title:const Text('الأصناف والمخزون')),floatingActionButton:FloatingActionButton(backgroundColor:blue,onPressed:()=>add(c),child:const Icon(Icons.add)),body:ListView(padding:const EdgeInsets.all(14),children:[TextField(onChanged:(v)=>setState(()=>q=v),decoration:const InputDecoration(hintText:'بحث عن صنف...',prefixIcon:Icon(Icons.search))),const SizedBox(height:8),const Wrap(spacing:5,children:[Chip(label:Text('الكل')),Chip(label:Text('سباكة')),Chip(label:Text('كهرباء')),Chip(label:Text('أدوات ورش'))]),if(rows.isEmpty)const Empty('لا توجد أصناف بعد'),...rows.map((r){final low=(r['qty'] as num)<=((r['minimum'] as num));return Card(color:card,child:ListTile(title:Text(r['name']),subtitle:Text('${r['category']??''} • ${money(r['price'])}'),leading:Icon(Icons.inventory_2_outlined,color:low?red:green),trailing:Text('الكمية ${r['qty']}')));})]));}Future<void> add(BuildContext c)async{await editor(c,'إضافة صنف',const[{'k':'name','l':'اسم الصنف'},{'k':'category','l':'التصنيف'},{'k':'qty','l':'الكمية','num':true},{'k':'minimum','l':'حد التنبيه','num':true},{'k':'price','l':'السعر','num':true}],(v)async{if(v['name']!.trim().isEmpty)return;await DB.d.then((d)=>d.insert('products',{'name':v['name'],'category':v['category'],'qty':double.tryParse(v['qty']!)??0,'minimum':double.tryParse(v['minimum']!)??0,'price':double.tryParse(v['price']!)??0,'created':DateTime.now().toIso8601String()}));await c.read<AppState>().refresh();});}}

class Dues extends StatelessWidget{const Dues({super.key});@override Widget build(BuildContext c){final s=c.watch<AppState>();return Scaffold(appBar:AppBar(title:const Text('الاستحقاقات')),floatingActionButton:FloatingActionButton(backgroundColor:blue,onPressed:()=>add(c),child:const Icon(Icons.add)),body:ListView(padding:const EdgeInsets.all(14),children:[if(s.dues.isEmpty)const Empty('لا توجد استحقاقات'),...s.dues.map((r)=>Card(color:card,child:ListTile(title:Text(money(r['amount'])),subtitle:Text('${r['customer']??''} • ${dtext(r['due'])}'),leading:Icon(Icons.event,color:r['status']=='paid'?green:gold),trailing:IconButton(icon:const Icon(Icons.check),onPressed:()async{await DB.d.then((d)=>d.update('dues',{'status':'paid'},where:'id=?',whereArgs:[r['id']]));await c.read<AppState>().refresh();}))))]));}Future<void> add(BuildContext c)async{await editor(c,'إضافة استحقاق',[const {'k':'customer','l':'العميل'},{'k':'amount','l':'المبلغ','num':true},{'k':'due','l':'التاريخ YYYY-MM-DD','v':DateTime.now().toIso8601String().substring(0,10)},{'k':'note','l':'ملاحظة'}],(v)async{await DB.d.then((d)=>d.insert('dues',{'customer':v['customer'],'amount':double.tryParse(v['amount']!)??0,'due':v['due'],'note':v['note'],'status':'pending'}));await c.read<AppState>().refresh();});}}

class Reports extends StatelessWidget{const Reports({super.key});@override Widget build(BuildContext c){return ListView(padding:const EdgeInsets.all(15),children:[const Text('التقارير',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900)),const SizedBox(height:10),for(final x in const[['تقرير العملاء',Icons.people],['تقرير الأرصدة',Icons.account_balance_wallet],['تقرير المخزون',Icons.inventory_2],['تقرير الأصناف الناقصة',Icons.warning_amber],['تقرير الاستحقاقات',Icons.event]])Card(color:card,child:ListTile(title:Text(x[0] as String),leading:Icon(x[1] as IconData,color:gold),trailing:const Icon(Icons.chevron_left),onTap:()=>showReport(c,x[0] as String))),const SizedBox(height:10),FilledButton.icon(onPressed:()=>pdf(c),icon:const Icon(Icons.picture_as_pdf),label:const Text('تصدير تقرير PDF'))]);}Future<void> showReport(BuildContext c,String title)async{final s=c.read<AppState>();String text;if(title.contains('العملاء'))text=s.customers.map((r)=>'${r['name']} - ${r['phone']??''}').join('\n');else if(title.contains('المخزون'))text=s.products.map((r)=>'${r['name']} - ${r['qty']}').join('\n');else if(title.contains('الاستحقاقات'))text=s.dues.map((r)=>'${money(r['amount'])} - ${dtext(r['due'])}').join('\n');else text=jsonEncode(s.st);await showDialog(context:c,builder:(_)=>AlertDialog(backgroundColor:card,title:Text(title),content:SingleChildScrollView(child:Text(text.isEmpty?'لا توجد بيانات':text))));}Future<void> pdf(BuildContext c)async{final s=c.read<AppState>(),doc=pw.Document();doc.addPage(pw.Page(build:(_)=>pw.Column(children:[pw.Text('Smart Assistant Report'),pw.Text('Customers: ${s.customers.length}'),pw.Text('Products: ${s.products.length}'),pw.Text('Pending dues: ${s.dues.where((x)=>x['status']=='pending').length}')]));await Printing.layoutPdf(onLayout:(f)=>doc.save());}}

class More extends StatelessWidget{const More({super.key});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[const SizedBox(height:10),const Center(child:Logo()),const SizedBox(height:10),const Center(child:Text('المساعد الذكي',style:TextStyle(fontSize:27,fontWeight:FontWeight.w900))),const Center(child:Text('نظام ذكي شامل لإدارة عملك',style:TextStyle(color:muted))),const SizedBox(height:18),ListTileCard('الاستحقاقات',Icons.event,()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Dues()))),ListTileCard('الاستيراد الذكي',Icons.file_upload,()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const ImportPage()))),ListTileCard('المساعد الذكي',Icons.smart_toy_outlined,()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Chat()))),ListTileCard('النسخ الاحتياطي',Icons.backup,()=>backup(c)),ListTileCard('الإعدادات',Icons.settings,()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Settings()))) ]);}
class ListTileCard extends StatelessWidget{final String t;final IconData i;final VoidCallback f;const ListTileCard(this.t,this.i,this.f,{super.key});@override Widget build(BuildContext c)=>Card(color:card,child:ListTile(title:Text(t),trailing:Icon(i,color:gold),leading:const Icon(Icons.chevron_left),onTap:f));}
class Logo extends StatelessWidget{const Logo({super.key});@override Widget build(BuildContext c)=>Container(width:105,height:105,decoration:BoxDecoration(color:const Color(0xFF091D3A),borderRadius:BorderRadius.circular(30),border:Border.all(color:blue,width:2)),child:const Icon(Icons.smart_toy_outlined,size:62,color:gold));}

Future<void> backup(BuildContext c)async{final d=await DB.d;final data={'customers':await d.query('customers'),'products':await d.query('products'),'dues':await d.query('dues'),'transactions':await d.query('transactions')};try{final dir=Directory('/storage/emulated/0/Download');await dir.create(recursive:true);final f=File(p.join(dir.path,'smart_assistant_backup.json'));await f.writeAsString(jsonEncode(data));if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('تم حفظ النسخة الاحتياطية في Download')));}catch(e){if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('تعذر الحفظ: $e')));}}

class ImportPage extends StatefulWidget{const ImportPage({super.key});@override State<ImportPage> createState()=>_IP();}
class _IP extends State<ImportPage>{String msg='اختر CSV أو XLSX ثم اختر نوع البيانات.';bool busy=false;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('الاستيراد الذكي')),body:ListView(padding:const EdgeInsets.all(16),children:[FilledButton.icon(onPressed:busy?null:()=>pick(c,'customers'),icon:const Icon(Icons.people),label:const Text('استيراد العملاء')),FilledButton.icon(onPressed:busy?null:()=>pick(c,'products'),icon:const Icon(Icons.inventory_2),label:const Text('استيراد الأصناف')),const SizedBox(height:15),Card(color:card,child:Padding(padding:const EdgeInsets.all(15),child:Text(msg))),const SizedBox(height:10),const Text('صيغة العملاء: name,phone,notes\nصيغة الأصناف: name,category,qty,minimum,price',style:TextStyle(color:muted))]));Future<void>pick(BuildContext c,String type)async{setState(()=>busy=true);try{final r=await FilePicker.platform.pickFiles(type:FileType.custom,allowedExtensions:['csv','xlsx']);if(r==null||r.files.single.path==null)return;final f=File(r.files.single.path!),name=r.files.single.name;final d=await DB.d;if(name.toLowerCase().endsWith('.csv')){final rows=const CsvToListConverter().convert(await f.readAsString());for(final row in rows.skip(1)){String z(int i)=>i<row.length?'${row[i]}':'';if(type=='customers')await d.insert('customers',{'name':z(0),'phone':z(1),'notes':z(2),'created':DateTime.now().toIso8601String()});else await d.insert('products',{'name':z(0),'category':z(1),'qty':double.tryParse(z(2))??0,'minimum':double.tryParse(z(3))??0,'price':double.tryParse(z(4))??0,'created':DateTime.now().toIso8601String()});}}else{final book=excel.Excel.decodeBytes(await f.readAsBytes());for(final sh in book.tables.values){for(final row in sh.rows.skip(1)){String z(int i)=>i<row.length?'${row[i]?.value??''}':'';if(type=='customers')await d.insert('customers',{'name':z(0),'phone':z(1),'notes':z(2),'created':DateTime.now().toIso8601String()});else await d.insert('products',{'name':z(0),'category':z(1),'qty':double.tryParse(z(2))??0,'minimum':double.tryParse(z(3))??0,'price':double.tryParse(z(4))??0,'created':DateTime.now().toIso8601String()});}}}await c.read<AppState>().refresh();setState(()=>msg='تم استيراد $name بنجاح.');}catch(e){setState(()=>msg='فشل الاستيراد: $e');}finally{if(mounted)setState(()=>busy=false);}}}

class Chat extends StatefulWidget{const Chat({super.key});@override State<Chat> createState()=>_Chat();}
class _Chat extends State<Chat>{final q=TextEditingController();final ms=<Map<String,String>>[{'r':'a','t':'مرحباً بك في المساعد الذكي. اسألني عن العملاء أو الأصناف أو الاستحقاقات.'}];bool busy=false;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('المساعد الذكي')),body:Column(children:[Expanded(child:ListView.builder(padding:const EdgeInsets.all(14),itemCount:ms.length,itemBuilder:(c,i)=>Align(alignment:ms[i]['r']=='u'?Alignment.centerLeft:Alignment.centerRight,child:Container(margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.all(12),constraints:const BoxConstraints(maxWidth:340),decoration:BoxDecoration(color:ms[i]['r']=='u'?blue:card,borderRadius:BorderRadius.circular(16)),child:Text(ms[i]['t']!))))),Padding(padding:const EdgeInsets.all(10),child:Row(children:[Expanded(child:TextField(controller:q,decoration:const InputDecoration(hintText:'اكتب سؤالك...'))),IconButton.filled(onPressed:busy?null:send,icon:const Icon(Icons.send))]))]));Future<void>send()async{final text=q.text.trim();if(text.isEmpty)return;setState((){ms.add({'r':'u','t':text});q.clear();busy=true;});final s=context.read<AppState>();try{if(s.key.isEmpty){ms.add({'r':'a','t':'أضف API Key من الإعدادات لتفعيل الذكاء الاصطناعي.'});return;}final data=jsonEncode(s.st);final r=await http.post(Uri.parse(s.base),headers:{'Authorization':'Bearer ${s.key}','Content-Type':'application/json'},body:jsonEncode({'model':s.model,'messages':[{'role':'system','content':'أنت مساعد إدارة عربي. لا تخترع بيانات. إحصاءات التطبيق: $data'},{'role':'user','content':text}]}));if(r.statusCode>=200&&r.statusCode<300){final j=jsonDecode(r.body);ms.add({'r':'a','t':'${j['choices'][0]['message']['content']??'لا توجد إجابة'}'});}else{ms.add({'r':'a','t':'فشل الاتصال (${r.statusCode}).'});}}catch(e){ms.add({'r':'a','t':'خطأ اتصال: $e'});}finally{if(mounted)setState(()=>busy=false);}}@override void dispose(){q.dispose();super.dispose();}}

class Settings extends StatefulWidget{const Settings({super.key});@override State<Settings> createState()=>_Settings();}
class _Settings extends State<Settings>{late TextEditingController k,m,b;@override void initState(){super.initState();final s=context.read<AppState>();k=TextEditingController(text:s.key);m=TextEditingController(text:s.model);b=TextEditingController(text:s.base);}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('الإعدادات')),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:k,obscureText:true,decoration:const InputDecoration(labelText:'API Key')),const SizedBox(height:10),TextField(controller:m,decoration:const InputDecoration(labelText:'Model')),const SizedBox(height:10),TextField(controller:b,decoration:const InputDecoration(labelText:'API Base URL')),const SizedBox(height:15),FilledButton(onPressed:()async{await c.read<AppState>().saveAI(k.text,m.text,b.text);if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('تم الحفظ')));},child:const Text('حفظ')),const SizedBox(height:15),const Card(color:card,child:Padding(padding:EdgeInsets.all(14),child:Text('لا تضع مفتاح API داخل GitHub. أدخله من داخل التطبيق.'))) ]));@override void dispose(){k.dispose();m.dispose();b.dispose();super.dispose();}}
class Empty extends StatelessWidget{final String t;const Empty(this.t,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(40),child:Center(child:Text(t,style:const TextStyle(color:muted))));}
